force-app/main/default/objects/Product2/fields/TDX_Asset__c.field-meta.xml
<CustomField>
    <fullName>TDX_Asset__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>TDX Asset</label>
    <referenceTo>TDX_Asset__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TDX_Asset__c/TDX_Asset__c.object-meta.xml
<CustomObject>
    <description>Represents any asset (e.g., a hotel or an airline)</description>
    <label>TDX Asset</label>
    <nameField>
        <label>Asset Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TDX Assets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TDX_Asset__c/fields/Amenities__c.field-meta.xml
<CustomField>
    <fullName>Amenities__c</fullName>
    <description>Amenities is the custom field of type multi-picklist that is used to store the Amenities provided by the Hotel.</description>
    <label>Amenities</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Gym</fullName>
            </value>
            <value>
                <fullName>Swimming Pool</fullName>
            </value>
            <value>
                <fullName>Game Zone</fullName>
            </value>
            <value>
                <fullName>Golf</fullName>
            </value>
            <value>
                <fullName>Playground</fullName>
            </value>
            <value>
                <fullName>Balling Alley</fullName>
            </value>
            <value>
                <fullName>Bar</fullName>
            </value>
            <value>
                <fullName>Camp Fire</fullName>
            </value>
            <value>
                <fullName>Mountain Tracking</fullName>
            </value>
            <value>
                <fullName>Ropeway Travel</fullName>
            </value>
            <value>
                <fullName>Beautiful Lakes</fullName>
            </value>
            <value>
                <fullName>Sports</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TDX_Asset__c/fields/Overall_Rating__c.field-meta.xml
<CustomField>
    <fullName>Overall_Rating__c</fullName>
    <defaultValue>3</defaultValue>
    <label>Overall Rating</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/GetCustomerBooking.cls
public class GetCustomerBooking {
    @InvocableMethod(label='Get Customer Previous Bookings' description='Fetch and return customer previous booking details')
    public static List<String> getPreviousbookings(List<String> customerId){
        Set<Id> assetIds = new Set<Id>();
        if(customerId != null && customerId.size()>0){
            User u = [Select Id,FirstName, LastName, Email, Agency_Id__c From User where Agency_Id__c =: customerId[0]];
            if(u != null){
                List<Account> accList = [Select id,Company_Email__c From Account Where Company_Email__c =: u.Email ];
                if(accList != null){
                    List<AssetDetail> assets = new List<AssetDetail>();
                    for(Order ord : [SELECT (SELECT Id, Product2.TDX_Asset__c, Product2.TDX_Asset__r.Name,Product2.TDX_Asset__r.Amenities__c, Product2.TDX_Asset__r.Overall_Rating__c FROM OrderItems) Id FROM Order WHERE AccountId = :accList[0].Id]){
                        for(OrderItem item : ord.OrderItems){
                            if(!assetIds.contains(item.Product2.TDX_Asset__c)){
                                AssetDetail detail = new AssetDetail();
                                detail.name = item.Product2.TDX_Asset__r.Name;
                                detail.rating = Integer.valueOf(item.Product2.TDX_Asset__r.Overall_Rating__c);
                                detail.amenities = item.Product2.TDX_Asset__r.Amenities__c;
                                assetIds.add(item.Product2.TDX_Asset__c);
                                assets.add(detail);
                            }
                        }
                    }
                    return new List<String>{JSON.serialize(assets)};
                }
           }
        }
        return new List<String>{'No previous bookings'};
    }
    
    
    public class AssetDetail {
        public String name;
        public Integer rating;
        public String amenities;
    }
}