force-app/main/default/objects/TDX_Asset__c/TDX_Asset__c.object-meta.xml
<CustomObject>
    <description>Represents any asset (e.g., a hotel or an airline)</description>
    <label>TDX Asset</label>
    <nameField>
        <label>Asset Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TDX Assets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TDX_Asset__c/fields/Amenities__c.field-meta.xml
<CustomField>
    <fullName>Amenities__c</fullName>
    <description>Amenities is the custom field of type multi-picklist that is used to store the Amenities provided by the Hotel.</description>
    <label>Amenities</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Gym</fullName>
            </value>
            <value>
                <fullName>Swimming Pool</fullName>
            </value>
            <value>
                <fullName>Game Zone</fullName>
            </value>
            <value>
                <fullName>Golf</fullName>
            </value>
            <value>
                <fullName>Playground</fullName>
            </value>
            <value>
                <fullName>Balling Alley</fullName>
            </value>
            <value>
                <fullName>Bar</fullName>
            </value>
            <value>
                <fullName>Camp Fire</fullName>
            </value>
            <value>
                <fullName>Mountain Tracking</fullName>
            </value>
            <value>
                <fullName>Ropeway Travel</fullName>
            </value>
            <value>
                <fullName>Beautiful Lakes</fullName>
            </value>
            <value>
                <fullName>Sports</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TDX_Asset__c/fields/Overall_Rating__c.field-meta.xml
<CustomField>
    <fullName>Overall_Rating__c</fullName>
    <defaultValue>3</defaultValue>
    <label>Overall Rating</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/GetAssetsFromNames.cls
public class GetAssetsFromNames {
    
    @InvocableMethod(label='Get Assets From String' description='Returns the list of assets from names')
    public static List<String> getAssetsFromCommaSeparatedString(List<String> fullString){
        List<AssetDetail> assetDetails = new List<AssetDetail>();
        List<String> stringList = new List<String>();
        if(fullString != null && fullString.size()>0){
            stringList = fullString[0].split(',');
        }
        for(TDX_Asset__c asset :[SELECT Id, Name, Amenities__c, Overall_Rating__c FROM TDX_Asset__c WHERE Name IN : stringList]){
            AssetDetail detail = new AssetDetail();
            detail.name = asset.Name;
            detail.rating = Integer.valueOf(asset.Overall_Rating__c);
            detail.amenities = asset.Amenities__c;
            assetDetails.add(detail);
        }
        
        return new List<String>{JSON.serialize(assetDetails)};
    }
    
    public class AssetDetail {
        public String name;
        public Integer rating;
        public String amenities;
    }

}