force-app/main/default/objects/Booked_Date__c/Booked_Date__c.object-meta.xml
<CustomObject>
    <description>This object is used to store the booked</description>
    <label>Booked Date</label>
    <nameField>
        <displayFormat>BD-{0000}</displayFormat>
        <label>Booked Date Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Booked Dates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Booked_Date__c/fields/Available_Slots__c.field-meta.xml
<CustomField>
    <fullName>Available_Slots__c</fullName>
    <formula>Product__r.Quantity__c - Booked_Slots__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Available Slots</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Booked_Date__c/fields/Booked_Slots__c.field-meta.xml
<CustomField>
    <fullName>Booked_Slots__c</fullName>
    <description>This Field Store the value of the Booked Slots. And Value of this field is Updated on the basis of the Record Creation of the Booked Dates.</description>
    <label>Booked Slots</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Booked_Date__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Booked Dates</relationshipLabel>
    <relationshipName>Booked_Dates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Arrival_Location__c.field-meta.xml
<CustomField>
    <fullName>Arrival_Location__c</fullName>
    <label>Arrival Location</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Cities</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Arrival_Time__c.field-meta.xml
<CustomField>
    <fullName>Arrival_Time__c</fullName>
    <label>Arrival Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Departure_Location__c.field-meta.xml
<CustomField>
    <fullName>Departure_Location__c</fullName>
    <label>Departure Location</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Cities</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Departure_Time__c.field-meta.xml
<CustomField>
    <fullName>Departure_Time__c</fullName>
    <label>Departure Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Product_Final_Unit_Price__c.field-meta.xml
<CustomField>
    <fullName>Product_Final_Unit_Price__c</fullName>
    <label>Product Final Unit Price</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/TDX_Asset__c.field-meta.xml
<CustomField>
    <fullName>TDX_Asset__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>TDX Asset</label>
    <referenceTo>TDX_Asset__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/recordTypes/Flight.recordType-meta.xml
<RecordType>
    <fullName>Flight</fullName>
    <active>true</active>
    <label>Flight</label>
</RecordType>

force-app/main/default/objects/TDX_Asset__c/TDX_Asset__c.object-meta.xml
<CustomObject>
    <description>Represents any asset (e.g., a hotel or an airline)</description>
    <label>TDX Asset</label>
    <nameField>
        <label>Asset Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TDX Assets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TDX_Asset__c/recordTypes/Airline.recordType-meta.xml
<RecordType>
    <fullName>Airline</fullName>
    <active>true</active>
    <label>Airline</label>
</RecordType>

force-app/main/default/classes/GetFlightDetails.cls
public without Sharing class GetFlightDetails {
	@InvocableMethod(label='Get Available flights' description='Returns the list of available flights' category='Product')
	public static List<List<flightResponse>> getAvailableFlights(List<flightRequest> requests) {
		Date journeyDate = requests[0].journeyDate;
        String departureLocation =requests[0].departureLocation;
        String arrivalLocation = requests[0].arrivalLocation;
        String airline = requests[0].airline;

        List<Product2> flightDetails = new List<Product2>();
        if(!String.isBlank(airline)){
            flightDetails = [SELECT Id, Name, TDX_Asset__c,Quantity__c, Arrival_Time__c, Departure_Time__c, TDX_Asset__r.Name, Product_Final_Unit_Price__c, Description , (SELECT Id, Start_Date__c, End_Date__c, Booked_Slots__c, Available_Slots__c FROM Booked_Dates__r WHERE Journey_Date__c =: journeyDate) FROM Product2 WHERE TDX_Asset__r.Name =: airline And Departure_Location__c =:departureLocation AND Arrival_Location__c =:arrivalLocation];
        }
        else{
            flightDetails = [SELECT Id, Name, TDX_Asset__c,Quantity__c, Arrival_Time__c, Departure_Time__c, TDX_Asset__r.Name, Product_Final_Unit_Price__c, Description , (SELECT Id, Start_Date__c, End_Date__c, Booked_Slots__c, Available_Slots__c FROM Booked_Dates__r WHERE Journey_Date__c =: journeyDate) FROM Product2 WHERE Departure_Location__c =:departureLocation AND Arrival_Location__c =:arrivalLocation];
        
        }
        List<flightResponse> flightList= new List<flightResponse>();
        if(!flightDetails.isEmpty()) {
            List<Booked_Date__c> bookedflight = new List<Booked_Date__c>();
            for(Product2 flight : flightDetails){
                bookedflight = flight.Booked_Dates__r;
                if(flight.Quantity__c > bookedflight.size()){
                    flightResponse hr = new flightResponse();
                    hr.airline = flight.TDX_Asset__r.Name;
                    hr.departureTime = flight.Departure_Time__c;
                    hr.arrivalTime = flight.Arrival_Time__c;
                    hr.price = (Integer)flight.Product_Final_Unit_Price__c;
                    hr.flightName = flight.Name;
                    flightList.add(hr);
                }
                
            }
           
        }
        return new List<List<flightResponse>>{ flightList };
    }
    public class flightRequest {
        @InvocableVariable(
            required=true
            description='Journey Date for which we want to check the flight. The variable needs to be an Apex Date type with format yyyy-MM-dd.'
        )
        public Date journeyDate;
        @InvocableVariable(
            required=true
            description='Departure Location of flight'
        )
        public String departureLocation;
        @InvocableVariable(
            required=true
            description='Arrival Location of flight'
        )
        public String arrivalLocation;
        @InvocableVariable(
            description='Name of airline for which user want to search the flight'
        )
        public String airline;
    }

    public class flightResponse {
        @InvocableVariable(
            description='Name of Airline'
        )
        public String airline;
        @InvocableVariable(
            description='Departure Time of flight'
        )
        public Time departureTime;
        @InvocableVariable(
            description='Arrival Time of flight'
        )
        public Time arrivalTime;
        @InvocableVariable(
            description='price of flight'
        )
        public Integer price;
        @InvocableVariable(
            description='Name of Flight. It just like the flight Code Number'
        )
        public String flightName;
    }
}