force-app/main/default/objects/Booked_Date__c/Booked_Date__c.object-meta.xml
<CustomObject>
    <description>This object is used to store the booked</description>
    <label>Booked Date</label>
    <nameField>
        <displayFormat>BD-{0000}</displayFormat>
        <label>Booked Date Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Booked Dates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Booked_Date__c/fields/Available_Slots__c.field-meta.xml
<CustomField>
    <fullName>Available_Slots__c</fullName>
    <formula>Product__r.Quantity__c - Booked_Slots__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Available Slots</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Booked_Date__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Booked Dates</relationshipLabel>
    <relationshipName>Booked_Dates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Hotel_Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Hotel_Product_Type__c</fullName>
    <label>Hotel Product Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Room</fullName>
            </value>
            <value>
                <fullName>Dining</fullName>
            </value>
            <value>
                <fullName>Swimming Pool</fullName>
            </value>
            <value>
                <fullName>Banquet Hall</fullName>
            </value>
            <value>
                <fullName>Conference Room</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Max_No_Of_Guest__c.field-meta.xml
<CustomField>
    <fullName>Max_No_Of_Guest__c</fullName>
    <label>Max No Of Guest</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Product_Final_Unit_Price__c.field-meta.xml
<CustomField>
    <fullName>Product_Final_Unit_Price__c</fullName>
    <label>Product Final Unit Price</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Room_Type__c.field-meta.xml
<CustomField>
    <fullName>Room_Type__c</fullName>
    <label>Room Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Hotel_Product_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Standard</fullName>
            </value>
            <value>
                <fullName>Deluxe</fullName>
            </value>
            <value>
                <fullName>Semi-Deluxe</fullName>
            </value>
            <value>
                <fullName>Suite</fullName>
            </value>
            <value>
                <fullName>King Size</fullName>
            </value>
            <value>
                <fullName>Queen Size</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/TDX_Asset__c.field-meta.xml
<CustomField>
    <fullName>TDX_Asset__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>TDX Asset</label>
    <referenceTo>TDX_Asset__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/recordTypes/Room.recordType-meta.xml
<RecordType>
    <fullName>Room</fullName>
    <active>true</active>
    <label>Room</label>
</RecordType>

force-app/main/default/objects/TDX_Asset__c/TDX_Asset__c.object-meta.xml
<CustomObject>
    <description>Represents any asset (e.g., a hotel or an airline)</description>
    <label>TDX Asset</label>
    <nameField>
        <label>Asset Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TDX Assets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TDX_Asset__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <description>for Hotel</description>
    <label>City</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Cities</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/TDX_Asset__c/fields/Overall_Rating__c.field-meta.xml
<CustomField>
    <fullName>Overall_Rating__c</fullName>
    <defaultValue>3</defaultValue>
    <label>Overall Rating</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TDX_Asset__c/recordTypes/Hotel.recordType-meta.xml
<RecordType>
    <fullName>Hotel</fullName>
    <active>true</active>
    <label>Hotel</label>
</RecordType>

force-app/main/default/classes/getHotelsWithRoomAvailibility.cls
public without sharing class getHotelsWithRoomAvailibility {
    @InvocableMethod(label='Get Available Hotels' description='Returns the list of available hotels in user input dates and city.' category='Asset')
	public static List<List<HotelResponse>> getAvailableHotels(List<HotelRequest> requests) {
		Date startDate = requests[0].startDate;
        Date endDate =requests[0].endDate;
        String city = requests[0].city;
        Set<Id> hotelIds = new Set<Id>();

        List<HotelResponse> hotelList = new List<HotelResponse>();
        List<TDX_Asset__c> hotelDetailsResult = new List<TDX_Asset__c>();
        Boolean isRoomFull = false;
        List<Product2> roomDetails = [SELECT Id, Name, ProductCode, TDX_Asset__c , TDX_Asset__r.Name, TDX_Asset__r.City__c, Room_Type__c, Hotel_Product_Type__c, Product_Final_Unit_Price__c, Max_No_Of_Guest__c, Description , (SELECT Id,Available_Slots__c FROM Booked_Dates__r  WHERE Start_Date__c >= :startDate AND End_Date__c <= :endDate) FROM Product2 WHERE  TDX_Asset__r.City__c =:city];
system.debug('roomDetails' + roomDetails )    ;    
if(!roomDetails.isEmpty()){
            For(Product2 room : roomDetails){
                System.debug('roomDetails' + roomDetails);
                
                if(room.Booked_Dates__r.isEmpty()){
                    hotelIds.add(room.TDX_Asset__c);
                }
                else{
                    isRoomFull = false;
                    For(Booked_Date__c bookedDate : room.Booked_Dates__r){
                        System.debug('inside second For');
                        if(bookedDate.Available_Slots__c == 0){
                            System.debug('inside 2nd if');
                            isRoomFull = true;
                            break;
                        }
                        else{
                            System.debug('inside second else');
                            continue;
                        }
                    }
                    if(!isRoomFull){
                        System.debug('inside last if');
                        hotelIds.add(room.TDX_Asset__c);
                    }
                }
            }
            if(!hotelIds.isEmpty()) {
                hotelDetailsResult = [SELECT Id,Name,City__c FROM TDX_Asset__c  Where Id IN: hotelIds];
                for(TDX_Asset__c  hotel : hotelDetailsResult){
                    HotelResponse hr = new HotelResponse();
                    hr.Name = hotel.Name;
                    //hr.rating = hotel.Overall_Rating__c;
                    hotelList.add(hr);
                }
            }
        }
        return new List<List<HotelResponse>>{ hotelList };
    }
    public class HotelRequest {
        @InvocableVariable(
            required=true
            description='Check In Date for which we want to check the hotel. The variable needs to be an Apex Date type with format yyyy-MM-dd.'
        )
        public Date startDate;
        @InvocableVariable(
            required=true
            description='Check out Date for which we want to check the hotel. The variable needs to be an Apex Date type with format yyyy-MM-dd.'
        )
        public Date endDate;
        @InvocableVariable(
            required=true
            description='City in which we want to search the hotel'
        )
        public String city;
    }

    public class HotelResponse {
        @InvocableVariable(
            description='Name of hotel'
        )
        public String name;
        //@InvocableVariable(
          //  description='Rating of the available hotel'
        //)
        //public Decimal rating;
    }
}