force-app/main/default/objects/Booked_Date__c/Booked_Date__c.object-meta.xml
<CustomObject>
    <description>This object is used to store the booked</description>
    <label>Booked Date</label>
    <nameField>
        <displayFormat>BD-{0000}</displayFormat>
        <label>Booked Date Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Booked Dates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Booked_Date__c/fields/Available_Slots__c.field-meta.xml
<CustomField>
    <fullName>Available_Slots__c</fullName>
    <formula>Product__r.Quantity__c - Booked_Slots__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Available Slots</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Booked_Date__c/fields/Booked_Slots__c.field-meta.xml
<CustomField>
    <fullName>Booked_Slots__c</fullName>
    <description>This Field Store the value of the Booked Slots. And Value of this field is Updated on the basis of the Record Creation of the Booked Dates.</description>
    <label>Booked Slots</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Booked_Date__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Booked Dates</relationshipLabel>
    <relationshipName>Booked_Dates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Hotel_Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Hotel_Product_Type__c</fullName>
    <label>Hotel Product Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Room</fullName>
            </value>
            <value>
                <fullName>Dining</fullName>
            </value>
            <value>
                <fullName>Swimming Pool</fullName>
            </value>
            <value>
                <fullName>Banquet Hall</fullName>
            </value>
            <value>
                <fullName>Conference Room</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Max_No_Of_Guest__c.field-meta.xml
<CustomField>
    <fullName>Max_No_Of_Guest__c</fullName>
    <label>Max No Of Guest</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Product_Final_Unit_Price__c.field-meta.xml
<CustomField>
    <fullName>Product_Final_Unit_Price__c</fullName>
    <label>Product Final Unit Price</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Room_Type__c.field-meta.xml
<CustomField>
    <fullName>Room_Type__c</fullName>
    <label>Room Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Hotel_Product_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Standard</fullName>
            </value>
            <value>
                <fullName>Deluxe</fullName>
            </value>
            <value>
                <fullName>Semi-Deluxe</fullName>
            </value>
            <value>
                <fullName>Suite</fullName>
            </value>
            <value>
                <fullName>King Size</fullName>
            </value>
            <value>
                <fullName>Queen Size</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/TDX_Asset__c.field-meta.xml
<CustomField>
    <fullName>TDX_Asset__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>TDX Asset</label>
    <referenceTo>TDX_Asset__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/recordTypes/Room.recordType-meta.xml
<RecordType>
    <fullName>Room</fullName>
    <active>true</active>
    <label>Room</label>
</RecordType>

force-app/main/default/objects/TDX_Asset__c/TDX_Asset__c.object-meta.xml
<CustomObject>
    <description>Represents any asset (e.g., a hotel or an airline)</description>
    <label>TDX Asset</label>
    <nameField>
        <label>Asset Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TDX Assets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TDX_Asset__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <description>for Hotel</description>
    <label>City</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Cities</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/TDX_Asset__c/recordTypes/Hotel.recordType-meta.xml
<RecordType>
    <fullName>Hotel</fullName>
    <active>true</active>
    <label>Hotel</label>
</RecordType>

force-app/main/default/classes/GetAvailableRoomsWithHotel.cls
public class GetAvailableRoomsWithHotel {
	@InvocableMethod(label='Get Available Rooms in Hotel' description='Returns the list of available Rooms in user selected hotel' category='Product')
	public static List<List<RoomResponse>> getAvailableHotels(List<RoomRequest> requests) {
		Date startDate = requests[0].startDate;
        Date endDate =requests[0].endDate;
        String hotelName = requests[0].hotelName;

        List<Product2> roomDetails = [SELECT Id, Name, ProductCode, TDX_Asset__c, TDX_Asset__r.Name, TDX_Asset__r.City__c, Room_Type__c, Hotel_Product_Type__c, Product_Final_Unit_Price__c, Max_No_Of_Guest__c, Description , (SELECT Id, Start_Date__c, End_Date__c, Booked_Slots__c, Available_Slots__c FROM Booked_Dates__r WHERE Start_Date__c >=:startDate AND End_Date__c <=:endDate) FROM Product2 WHERE TDX_Asset__r.Name =: hotelName];
		
        List<RoomResponse> roomList= new List<RoomResponse>();
        if(!roomDetails.isEmpty()) {
            for(Product2 room : roomDetails){
                RoomResponse hr = new RoomResponse();
                hr.RoomName = room.Name;
                hr.price = (Integer)room.Product_Final_Unit_Price__c;
                roomList.add(hr);
            }
           
        }
        return new List<List<RoomResponse>>{ roomList };
    }
    public class RoomRequest {
        @InvocableVariable(
            required=true
            description='Check In Date for which we want to check the hotel. The variable needs to be an Apex Date type with format yyyy-MM-dd.'
        )
        public Date startDate;
        @InvocableVariable(
            required=true
            description='Check out Date for which we want to check the hotel. The variable needs to be an Apex Date type with format yyyy-MM-dd.'
        )
        public Date endDate;
        @InvocableVariable(
            required=true
            description='Name of hotel from which room will be displayed'
        )
        public String hotelName;
    }

    public class RoomResponse {
        @InvocableVariable(
            description='Name of Room Type'
        )
        public String RoomName;
        @InvocableVariable(
            description='Number of person can stay in that room'
        )
        public Integer price;
    }
}